### ISSUE TITLE
Authorize and POST

### ISSUE THREAD

**Issue by tmatous** [twitchax/AspNetCore.Proxy#64] opened 2020-08-11 15:44 UTC
I have been trying to set up forwarding for some API endpoints. Some are GET and some are POST.  They are using Windows auth with Authorize() on both the gateway API project and the target API project. It seems like every request is overwriting the client's cached Authorization information, which is forcing the browser through a 401-negotiate cycle on every request from the browser to the gateway, and then another negotiate between the gateway and the target API. Is this expected?

The request does ultimately go through for a GET request, but for a POST request I am always getting "An error occurred while sending the request". Looking in Fiddler I see the 401-negotiate process between the browser and gateway, but then there is only a single 401 rejection from the gateway to the target API. The gateway isn't issuing an additional request with the corrected Authorization information.

I am using a customized HttpClient with "UseDefaultCredentials = true", and HttpProxyAsync() in the controller.

Is calling one secured API from another secured API a supported scenario?

**Comment by twitchax** [comment] 2020-08-11 17:56
It should be.  I might need to do some investigation to understand what happens here.  There aren't any `Authorize` tests right now, so if you are willing to contribute some, that would help too.

**Comment by tmatous** [comment] 2020-08-17 21:18
I'm thinking that would require creating a second TestServer in HttpIntegrationTests to provide the final secure endpoint. Does that make sense?

**Comment by twitchax** [comment] 2020-08-18 06:13
Yep, that is correct.

**Comment by tmatous** [comment] 2020-08-18 22:58
I added some tests in my fork, take a look and let me know what you think. The test that is failing is "CanProxyToTargetPostWithJsonDataAndAuth".

https://github.com/tmatous/AspNetCore.Proxy

**Comment by twitchax** [comment] 2020-08-20 17:26
Awesome: thanks.  I will take a look as soon as I can.

**Comment by bishwasgautam** [comment] 2020-10-15 04:49
Has there been any progress on this? @twitchax 

I am also getting a 401 on a GET call, the API being called has been secured with IdentityServerAuthentication. I am not sure if this is related. Any insight would be appreciated!

**Comment by twitchax** [comment] 2020-10-15 19:14
Sorry, I haven't had a chance yet.  Hopefully will have some free time soon.

**Comment by twitchax** [comment] 2020-11-03 09:36
Ok, all.  Finally had a chance to look at this.  @tmatous, thanks for the repro, and the tests.

After debugging, it appears as though this is actually caused by an existing bug on Microsoft (see: https://github.com/dotnet/runtime/issues/25413).  It's currently closed, but it is not fixed, as far as I can tell.

The workaround suggested by a user in that thread is to fully read the content out of the existing stream, and put it in a new stream.  If this were a problem with this library, then I would make a fix in the library, but I would prefer not to make add a funky workaround into this library when it could be fixed by a bug fix from Microsoft.  However, applying the workaround from the thread to this library can be achieved by using `BeforeSend`.  For example, you can do this.

```csharp
HttpProxyOptionsBuilder.Instance
    .WithHttpClientName("TargetHttpClient") // This client uses authorization.
    .WithBeforeSend(async (c, hrm) =>
    {
        var content = await hrm.Content.ReadAsStringAsync();
        hrm.Content = new StringContent(content, System.Text.Encoding.UTF8, "application/json");
    }).Build();
```

Sorry for the slow investigation, but I have been pretty slammed.  Hope this helps!

I will leave this open for now so we can discuss.

**Closed** 2020-12-04 07:03 UTC
